const bikes: Bike[] = [
  {
    id: "1",
    type: "old",
    image:
      "https://www.reidbikes.com/wp-content/uploads/2022/10/Ladies-Classic-eBike-3-900x588.png",
    description:
      "The Classic is just at home nipping to the shops or beach as it is delivering you to the restaurant or the office. All with effortless pace, no parking problems, no pollution, and no sweat. Truly the coolest way to travel. Designed with integrated headset, cables, and battery, it’s truly sleek. Drivetrain is provided by Shimano with 8 gears perfectly matched to the Bafang motors 250w output. The Classic has a 10.4ah battery meaning range is not an issue and charges are less frequent. Stopping is taken care of by powerful hydraulic disc brakes reinforcing that truly modern performance.",
    priceId: "",
    title: "LADIES CLASSIC EBIKE MY23",
  },
  {
    id: "1",
    type: "old",
    image: "",
    description: "",
    priceId: "",
    title: "",
  },
  {
    id: "1",
    type: "old",
    image: "",
    description: "",
    priceId: "",
    title: "",
  },
  {
    id: "1",
    type: "old",
    image: "",
    description: "",
    priceId: "",
    title: "",
  },
  {
    id: "1",
    type: "old",
    image: "",
    description: "",
    priceId: "",
    title: "",
  },
  {
    id: "1",
    type: "old",
    image: "",
    description: "",
    priceId: "",
    title: "",
  },
  {
    id: "1",
    type: "old",
    image: "",
    description: "",
    priceId: "",
    title: "",
  },
  {
    id: "1",
    type: "old",
    image: "",
    description: "",
    priceId: "",
    title: "",
  },
  {
    id: "1",
    type: "old",
    image: "",
    description: "",
    priceId: "",
    title: "",
  },
  {
    id: "1",
    type: "old",
    image: "",
    description: "",
    priceId: "",
    title: "",
  },
  {
    id: "1",
    type: "old",
    image: "",
    description: "",
    priceId: "",
    title: "",
  },
];
